name: Run Weather Script

on:
  schedule:
    - cron: '0 10 * * *'  # Run at 10 AM UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-weather-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Check out the repository code
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the desired Python version
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies
    
    - name: Run Weather Script
      run: python weather.py  # Execute the script
    
    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Run weather.py and update repository"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's automatic token
